export const work = [
  { id: '01', category: 'COMMERCIAL PRICING', title: 'Precision at enterprise scale.', description: 'Validating Microsoft commercial pricing, licensing agreements, and complex deal structures across global markets.', tags: ['Pricing analysis', 'Volume Licensing', 'Excel'], metric: '99%+', metricLabel: 'pricing accuracy', visual: 'pricing', details: 'Reviewing and approving pricing proposals, renewals, amendments, and contract modifications. Evaluating customer requirements, discounts, and financial approvals for 200+ commercial transactions each month while mitigating commercial risk.', tools: 'Advanced Excel · Titan · APT · VLC Analytics' },
  { id: '02', category: 'DATA & BUSINESS INTELLIGENCE', title: 'From numbers to decisions.', description: 'Turning pricing and operational data into clearer reporting and actionable insights for business stakeholders.', tags: ['Power BI', 'SQL', 'Data analysis'], metric: '3', metricLabel: 'global regions supported', visual: 'reporting', details: 'Using Advanced Excel, Power BI, and SharePoint to analyze pricing data, improve reporting accuracy, and support commercial decision-making. Collaborating with Sales, Finance, Legal, and Deal Desk teams across APAC, EMEA, and AMER.', tools: 'Power BI · SQL · Advanced Excel · SharePoint' },
  { id: '03', category: 'OPERATIONS & LEADERSHIP', title: 'Better processes. Stronger teams.', description: 'Leading analysts, standardizing workflows, and keeping high-volume commercial operations on track.', tags: ['Process improvement', 'SOPs', 'Team leadership'], metric: '95%+', metricLabel: 'SLA adherence', visual: 'operations', details: 'Leading and mentoring 8 analysts as a Process Subject Matter Expert. Managing workload allocation, reviewing deliverables, developing SOPs, and driving continuous improvement to maintain 99%+ quality and strict SLA compliance.', tools: 'Microsoft Copilot · SharePoint · Process optimization' },
] as const;

export const experience = [
  { date: 'OCT 2023 — PRESENT', role: 'Associate Consultant', company: 'Capgemini · Microsoft', location: 'Bengaluru, India', text: 'Driving commercial pricing excellence, global stakeholder collaboration, and process improvement. Leading 8 analysts as a Process Subject Matter Expert.', tags: ['200+ transactions / month', '99%+ pricing accuracy'] },
  { date: 'MAR 2022 — OCT 2023', role: 'Senior Analyst', company: 'Capgemini · Microsoft', location: 'Bengaluru, India', text: 'Managed Volume Licensing renewals, contract amendments, and commercial agreements for global enterprise customers with 99%+ transaction accuracy.', tags: ['Volume Licensing', 'Contract compliance'] },
  { date: 'FEB 2019 — JAN 2022', role: 'Data Analyst', company: 'Vodafone Idea Ltd', location: 'Varanasi, India', text: 'Analyzed operational data, created performance reports, and coordinated order fulfillment and invoicing to support better business decisions.', tags: ['Operational reporting', 'Microsoft Excel'] },
] as const;