import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, ArrowUp, Download, Moon, Sun, MapPin, BriefcaseBusiness, ChartNoAxesCombined, Database, Workflow, Users, Mail, Phone, GraduationCap, Award, Menu, X, Globe, CheckCheck, Linkedin } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { WorkVisual } from '@/components/work-visual';
import { work, experience } from '@/lib/portfolio';
import heroImage from '@/assets/data-landscape.jpg';
import resume from '@/assets/resume.asset.json';

export const Route = createFileRoute('/')({
 head: () => ({ meta: [
  { title: 'Priyanka Tiwari | Pricing & Data Analyst' },
  { name: 'description', content: 'Priyanka Tiwari — Associate Consultant and Pricing & Data Analyst. Seven years of commercial pricing, business intelligence, and operational excellence.' },
  { property: 'og:title', content: 'Priyanka Tiwari | Pricing & Data Analyst' },
  { property: 'og:description', content: 'Precision in pricing. Clarity in data. Explore Priyanka’s experience, expertise, and commercial impact.' },
  { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
 ] }), component: Portfolio,
});
const nav = [{ label: 'About', id: 'about' }, { label: 'Expertise', id: 'expertise' }, { label: 'Featured Work', id: 'work' }, { label: 'Experience', id: 'experience' }, { label: 'Contact', id: 'contact' }];
const skills = [
 { icon: ChartNoAxesCombined, title: 'Pricing & Commercial', items: ['Pricing validation', 'Deal structuring', 'Volume Licensing', 'Commercial risk', 'Pricing compliance'] },
 { icon: Database, title: 'Data & Intelligence', items: ['Advanced Excel', 'Power BI', 'SQL', 'Python', 'Pandas', 'NumPy', 'VLC Analytics', 'Titan · APT · COSMIC'] },
 { icon: Workflow, title: 'Process & Automation', items: ['Prompt engineering', 'Process optimization', 'SOP development', 'Microsoft Copilot', 'Agentic AI', 'AI Automation'] },
 { icon: Users, title: 'Leadership & Operations', items: ['Team leadership', 'Stakeholder management', 'SLA management', 'SharePoint', 'Global collaboration'] },
];
function Portfolio() {
 const [dark, setDark] = useState(true);
 const [menu, setMenu] = useState(false);
 const [selected, setSelected] = useState<(typeof work)[number] | null>(null);
 const [draftOpened, setDraftOpened] = useState(false);
 useEffect(() => { document.documentElement.classList.toggle('dark', dark); }, [dark]);
 useEffect(() => {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.animate([{ opacity: 0, transform: 'translateY(18px)' }, { opacity: 1, transform: 'translateY(0)' }], { duration: 650, easing: 'ease-out' }); observer.unobserve(entry.target); } }), { threshold: .12 });
  document.querySelectorAll('[data-reveal]').forEach(el => observer.observe(el));
  return () => observer.disconnect();
 }, []);
 function sendMessage(e: FormEvent<HTMLFormElement>) {
  e.preventDefault();
  const data = new FormData(e.currentTarget);
  const subject = encodeURIComponent(String(data.get('subject') || 'Portfolio enquiry'));
  const body = encodeURIComponent(`Hi Priyanka,\n\n${data.get('message')}\n\nFrom: ${data.get('name')}\nEmail: ${data.get('email')}`);
  window.location.href = `mailto:twrpriyanka1998@mail.com?subject=${subject}&body=${body}`;
  setDraftOpened(true);
 }
 return <>
  <header className="site-header" id="top"><div className="container-main header-inner">
   <a href="#top" className="wordmark" aria-label="Priyanka Tiwari home"><ChartNoAxesCombined /><div>PRIYANKA<span>.</span>TIWARI</div></a>
   <nav className="desktop-nav" aria-label="Main navigation">{nav.map(n => <a key={n.id} href={`#${n.id}`}>{n.label}</a>)}</nav>
   <div className="header-actions"><Button variant="ghost" size="icon" className="theme-button" aria-label={dark ? 'Switch to light theme' : 'Switch to dark theme'} title={dark ? 'Light theme' : 'Dark theme'} onClick={() => setDark(!dark)}>{dark ? <Sun /> : <Moon />}</Button><Button asChild variant="outline" className="header-resume"><a href={resume.url} target="_blank" rel="noreferrer"><Download /> Résumé</a></Button><Button variant="ghost" size="icon" className="menu-toggle" aria-label="Toggle navigation" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</Button></div>
  </div>{menu && <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(n => <a key={n.id} href={`#${n.id}`} onClick={() => setMenu(false)}>{n.label}</a>)}<a href={resume.url} target="_blank" rel="noreferrer">Download résumé ↗</a></nav>}</header>
  <main>
   <section className="hero"><img className="hero-image" src={heroImage} width={1536} height={1024} alt="High-contrast black and white abstract data landscape with flowing light trails over a fine grid" fetchPriority="high" /><div className="container-main hero-content reveal"><div className="eyebrow"><span className="status-dot" /> DATA-DRIVEN. DETAIL-ORIENTED. IMPACT-FOCUSED.</div><h1>PRIYANKA<br /><span>TIWARI.</span></h1><p className="hero-role">Pricing Analyst & Data Professional</p><p className="hero-description">Bringing precision to pricing. Turning complex data into confident business decisions — with 7 years of commercial and analytical experience.</p><div className="hero-buttons"><Button asChild><a href="#work">Explore My Work <ArrowUpRight /></a></Button><Button asChild variant="outline" className="hero-outline"><a href="#contact">Let’s Connect <ArrowRight /></a></Button></div><div className="hero-meta"><span><MapPin /> Bengaluru, India</span><span><BriefcaseBusiness /> Associate Consultant · Capgemini</span></div><div className="hero-caption">WHERE DATA MEETS BUSINESS IMPACT</div></div></section>
   <section className="metrics" aria-label="Professional impact"><div className="container-main metric-grid">{[{ value: '7', suffix: '+', label: 'Years of experience' }, { value: '99', suffix: '%+', label: 'Pricing accuracy' }, { value: '200', suffix: '+', label: 'Commercial transactions / month' }, { value: '8', suffix: '', label: 'Analysts led & mentored' }].map(m => <div className="metric" key={m.label}><strong>{m.value}<span>{m.suffix}</span></strong><p>{m.label}</p></div>)}</div></section>
   <section id="about" className="section"><div className="container-main about-grid" data-reveal><div><div className="eyebrow">01 / A LITTLE ABOUT ME</div><h2>An analytical mind.<br />A business-first approach.</h2></div><div className="about-copy"><p>I’m Priyanka, an Associate Consultant who connects <strong>commercial pricing, data analysis, and operational excellence.</strong> My work is rooted in one belief: better decisions start with accurate data.</p><p>At Capgemini, supporting Microsoft’s commercial business, I navigate complex pricing and licensing challenges, collaborate with global teams, and turn detailed analysis into practical outcomes. Beyond the numbers, I enjoy mentoring people and building processes that work better.</p><div className="about-footer"><span><Globe /> APAC · EMEA · AMER</span><span><CheckCheck /> Precision with purpose</span></div></div></div></section>
   <section id="expertise" className="section expertise"><div className="container-main" data-reveal><div className="section-heading"><div><div className="eyebrow">02 / MY TOOLKIT</div><h2>Expertise that delivers.</h2></div><p className="section-intro">A blend of analytical tools, commercial knowledge,<br />and the human skills that bring them together.</p></div><div className="expertise-grid">{skills.map(s => <div className="expertise-item" key={s.title}><s.icon className="expertise-icon" /><h3>{s.title}</h3><div className="skill-list">{s.items.map(item => <span className="skill" key={item}>{item}</span>)}</div></div>)}</div></div></section>
   <section id="work" className="section"><div className="container-main" data-reveal><div className="section-heading"><div><div className="eyebrow">03 / SELECTED IMPACT</div><h2>Real work. Measurable outcomes.</h2></div><p className="section-intro">Highlights from my professional experience.<br />Built on accuracy, insight, and continuous improvement.</p></div><div className="work-grid">{work.map(w => <article className="work-card" key={w.id}><WorkVisual type={w.visual} /><div className="work-body"><span className="work-category">{w.category}</span><h3>{w.title}</h3><p>{w.description}</p><div className="skill-list">{w.tags.map(t => <span className="skill" key={t}>{t}</span>)}</div><div className="work-bottom"><div><strong>{w.metric}</strong><span>{w.metricLabel}</span></div><Button variant="ghost" size="icon" className="work-open" title={`Explore ${w.category.toLowerCase()}`} aria-label={`Explore ${w.category.toLowerCase()}`} onClick={() => setSelected(w)}><ArrowUpRight /></Button></div></div></article>)}</div></div></section>
   <section id="experience" className="section career"><div className="container-main" data-reveal><div className="section-heading"><div><div className="eyebrow">04 / THE JOURNEY SO FAR</div><h2>Experience built on progress.</h2></div><Button asChild variant="outline"><a href={resume.url} target="_blank" rel="noreferrer"><Download /> Full résumé</a></Button></div><div className="career-grid"><div>{experience.map(e => <article className="timeline-item" key={e.role}><span className="timeline-date">{e.date}</span><h3>{e.role}</h3><div className="timeline-company">{e.company}</div><div className="timeline-location">{e.location}</div><p>{e.text}</p><div className="skill-list">{e.tags.map(t => <span className="skill" key={t}>{t}</span>)}</div></article>)}</div><aside className="career-side"><div className="education"><h3><GraduationCap /> EDUCATION</h3><h4>Bachelor of Science<br />Computer Science</h4><p>St. Joseph’s College for Women (Autonomous)<br />Visakhapatnam, Andhra Pradesh</p><span>2015 — 2018</span></div><h3><Award /> RECOGNITION</h3>{['Excellence in Delivery', 'The Transformers', 'Ace of the Invent', 'Pat on the Back', 'Best Team Award'].map(a => <div className="award" key={a}><Award />{a}</div>)}</aside></div></div></section>
   <section id="contact" className="section"><div className="container-main contact-grid" data-reveal><div><div className="eyebrow">05 / LET’S TALK</div><h2>Good things start<br />with a conversation.</h2><p className="contact-text">Have an opportunity, a challenging business problem, or just a shared interest in data? I’d love to hear from you.</p><a className="contact-link" href="https://www.linkedin.com/in/priyanka-twr" target="_blank" rel="noreferrer"><Linkedin /> linkedin.com/in/priyanka-twr <ArrowUpRight /></a><a className="contact-link" href="mailto:twrpriyanka1998@mail.com"><Mail /> twrpriyanka1998@mail.com <ArrowUpRight /></a><a className="contact-link" href="tel:+918919414816"><Phone /> +91 89194 14816</a><div className="contact-link"><MapPin /> Bengaluru, Karnataka, India</div></div><form className="contact-form" onSubmit={sendMessage}><div className="form-row"><div><label htmlFor="name">Your name</label><input id="name" name="name" required placeholder="Alex Johnson" autoComplete="name" /></div><div><label htmlFor="email">Email address</label><input id="email" name="email" type="email" required placeholder="alex@company.com" autoComplete="email" /></div></div><div><label htmlFor="subject">Subject</label><input id="subject" name="subject" required placeholder="Let’s explore an opportunity" /></div><div><label htmlFor="message">Your message</label><textarea id="message" name="message" required placeholder="Tell me a little about what you have in mind…" /></div><div><Button type="submit">Compose Email <ArrowUpRight /></Button></div><p className="form-note" role="status">{draftOpened ? 'Your email draft is ready in your email app. Send it there to get in touch.' : 'Opens your email app with your message ready to send.'}</p></form></div></section>
  </main><footer><div className="container-main footer-inner"><span>© {new Date().getFullYear()} Priyanka Tiwari. Thoughtful analysis. Meaningful impact.</span><a href="https://www.linkedin.com/in/priyanka-twr" target="_blank" rel="noreferrer"><Linkedin /> LinkedIn</a><a href="#top">Back to top <ArrowUp /></a></div></footer>
  <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent>{selected && <><span className="work-category">{selected.category}</span><DialogTitle>{selected.title}</DialogTitle><DialogDescription className="dialog-text">{selected.details}</DialogDescription><p className="dialog-tools">{selected.tools}</p><p className="form-note">Professional experience highlight. Visuals are illustrative, not confidential client dashboards.</p><Button asChild><a href="#contact" onClick={() => setSelected(null)}>Discuss my experience <ArrowRight /></a></Button></>}</DialogContent></Dialog>
 </>;
}
